const PDFDocument = require("pdfkit");

const money = (n) => "Rs. " + Number(n).toFixed(2);

// Streams a GST invoice for a voucher directly into the HTTP response.
function streamInvoicePdf(res, { company, voucher }) {
  const doc = new PDFDocument({ size: "A4", margin: 40 });
  const isSales = voucher.type === "sales";
  const title = isSales ? "TAX INVOICE" : "PURCHASE VOUCHER";

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `inline; filename="${voucher.voucher_no}.pdf"`
  );
  doc.pipe(res);

  // Header
  doc.font("Helvetica-Bold").fontSize(18).text(company.name, { align: "left" });
  doc.font("Helvetica").fontSize(9).fillColor("#444");
  if (company.address) doc.text(company.address);
  if (company.state) doc.text(`State: ${company.state}`);
  if (company.gstin) doc.text(`GSTIN: ${company.gstin}`);
  if (company.phone) doc.text(`Phone: ${company.phone}`);

  doc.moveDown(0.5);
  doc.fillColor("#000").font("Helvetica-Bold").fontSize(13).text(title, { align: "center" });
  doc.moveDown(0.5);

  // Meta
  doc.font("Helvetica").fontSize(10);
  doc.text(`Voucher No: ${voucher.voucher_no}`);
  doc.text(`Date: ${formatDate(voucher.voucher_date)}`);
  doc.moveDown(0.4);
  doc.font("Helvetica-Bold").text(isSales ? "Billed To:" : "Supplier:");
  doc.font("Helvetica").text(voucher.party_name);
  if (voucher.party_address) doc.text(voucher.party_address);
  if (voucher.party_gstin) doc.text(`GSTIN: ${voucher.party_gstin}`);
  if (voucher.party_phone) doc.text(`Phone: ${voucher.party_phone}`);
  doc.moveDown(0.8);

  // Table
  const startX = doc.page.margins.left;
  const widths = [26, 180, 60, 50, 70, 45, 84]; // #, item, qty, unit... total 515
  const cols = ["#", "Item", "Qty", "Unit", "Rate", "GST%", "Amount"];
  let y = doc.y;

  const row = (cells, bold = false) => {
    doc.font(bold ? "Helvetica-Bold" : "Helvetica").fontSize(9);
    let x = startX;
    const h = 18;
    cells.forEach((cell, i) => {
      const align = i >= 2 ? "right" : "left";
      doc.text(String(cell), x + 3, y + 5, { width: widths[i] - 6, align });
      x += widths[i];
    });
    doc
      .moveTo(startX, y + h)
      .lineTo(startX + widths.reduce((a, b) => a + b, 0), y + h)
      .strokeColor("#cccccc")
      .stroke();
    y += h;
    if (y > doc.page.height - 120) {
      doc.addPage();
      y = doc.page.margins.top;
    }
  };

  doc
    .moveTo(startX, y)
    .lineTo(startX + widths.reduce((a, b) => a + b, 0), y)
    .strokeColor("#000")
    .stroke();
  row(cols, true);
  voucher.items.forEach((it, idx) => {
    row([
      idx + 1,
      it.item_name + (it.sku ? ` (${it.sku})` : ""),
      Number(it.quantity),
      it.unit || "-",
      Number(it.rate).toFixed(2),
      Number(it.gst_percent).toFixed(1),
      Number(it.amount).toFixed(2),
    ]);
  });

  // Totals — assumes intra-state supply, so GST is split CGST + SGST
  const half = (Number(voucher.gst_amount) / 2).toFixed(2);
  y += 8;
  doc.font("Helvetica").fontSize(10);
  const totalsX = startX + 300;
  const line = (label, value, bold = false) => {
    doc.font(bold ? "Helvetica-Bold" : "Helvetica");
    doc.text(label, totalsX, y, { width: 120, align: "right" });
    doc.text(value, totalsX + 125, y, { width: 90, align: "right" });
    y += 16;
  };
  line("Subtotal", money(voucher.subtotal));
  line("CGST", money(half));
  line("SGST", money(half));
  line("Total", money(voucher.total), true);

  if (voucher.notes) {
    y += 10;
    doc.font("Helvetica").fontSize(9).fillColor("#444").text(`Notes: ${voucher.notes}`, startX, y);
    doc.fillColor("#000");
  }

  doc
    .font("Helvetica")
    .fontSize(8)
    .fillColor("#888")
    .text("Generated by SmartERP", startX, doc.page.height - 60, { align: "center", width: 515 });

  doc.end();
}

function formatDate(d) {
  const date = new Date(d);
  return date.toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
}

module.exports = { streamInvoicePdf };
